---
- hosts: postgres
  become: yes

  tasks:
    - name: Add key for Postgres repo
      apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

    - name: Add Postgres repo to sources list
      apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt bionic-pgdg main" state=present

    - name: install postgresql packages 
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
        - postgresql-12
        - libpq-dev
        - postgresql-contrib-12
        - libxslt-dev 
        - libxml2-dev
        - python3-pip
        - gcc
        - python3-dev
        - python3-setuptools

    - name: install deps
      pip: name={{ item }} state=absent
      with_items:
       - python-etcd
       - dnspython
       - psycopg2
       - PyYAML
       - python-dateutil
       - psycopg2-binary
       - patroni
       - python-consul
